UPDATE: <our-svg> - Caching + Enforcing Viewbox
umbraco-community/Our-Umbraco-TagHelpers pull request #45
Opened 2022-10-12 21:00 UTC by AndyBoot

### `<our-svg>`
- Updated Readme with changes
- Added new configurations to appsettings.json to set global output caching of SVG contents & 'fixing' SVG's to ensure they have a viewbox property rather than width & height properties.
- Added new tag helper properties to override global configurations & apply CSS classes to the SVG element
- Added new MediaSavedNotification to clear SVG cache on save of the media item.

2022-10-14 10:12 UTC, warrenbuckley approved these changes
Looks good to me.
I will try it out and then get this merged in 💪

2022-10-14 10:12 UTC, warrenbuckley commented on Our.Umbraco.TagHelpers/Notifications/InlineSvgTagHelperNotifications.cs
> +                        _logger.LogDebug($"Removed {mediaItem.Name} from RuntimeCache");
```suggestion
                        _logger.LogDebug("Removed {MediaItemName} from RuntimeCache", mediaItem.Name);
```

2022-10-14 10:15 UTC, warrenbuckley commented
Investigating the build/GitHub Actions pipeline error... 👀

2022-10-14 10:23 UTC, warrenbuckley requested changes
@AndyBoot it's missing `using Our.Umbraco.TagHelpers.Utils` and the StringUtils
```csharp
var width = StringUtils.GetDecimal(svgNode.GetAttributeValue("width", "0"));
var height = StringUtils.GetDecimal(svgNode.GetAttributeValue("height", "0"));
```

2022-10-15 21:46 UTC, AndyBoot commented
Hey @warrenbuckley, that should now be fixed. Don't know how I missed that one!
Not overly familiar with unit testing and the Tests project which also had errors due to the newly added dependencies within the tag helper contructor. I've just added nulls for each of these for each test method, hope that's ok!?

2022-10-17 10:57 UTC, warrenbuckley approved these changes

2022-10-17 10:58 UTC, warrenbuckley commented
@AndyBoot I fixed up the unit tests, but we can revisit them to add more tests to test the Options/.AppSettings/Config work as you expect them to

2022-10-17 11:04 UTC, merged